"""Alter Device port column

Revision ID: 45ee9555b0e7
Revises: fe3137381e6f
Create Date: 2026-09-11 10:50:03.955139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ee9555b0e7'
down_revision = 'fe3137381e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('port',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('port',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
