"""Alter Device port column null true

Revision ID: 6a8ad8044ac9
Revises: 45ee9555b0e7
Create Date: 2026-09-11 11:05:04.491050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8ad8044ac9'
down_revision = '45ee9555b0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('port',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('port',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
